import React from 'react';

function LearnMode({
    quizName,
    currentQuizData = {},
}: {
    quizName: string;
    currentQuizData: { [key: string]: any };
}) {
    return (
        <section className='mngo-h-full mngo-bg-black mngo-flex md:mngo-flex-row mngo-flex-col'>
            <aside className='mngo-h-full mngo-overflow-auto md:mngo-w-3/12 mngo-bg-slate-100'>
                <ul className='mngo-bg-gray-900 md:mngo-mt-28 mngo-mt-24'>
                    <li>dad</li>
                    <li>dad</li>
                    <li>dad</li>
                    <li>dad</li>
                    <li>dad</li>
                    <li>dad</li>
                    <li>dad</li>
                    <li>dad</li>
                    <li>dad</li>
                    <li>dad</li>
                    <li>dad</li>
                    <li>dad</li>
                    <li>dad</li>
                    <li>dad</li>
                    <li>dad</li>
                    <li>dad</li>
                    <li>dad</li>
                    <li>dad</li>
                    <li>dad</li>
                    <li>dad</li>
                    <li>dad</li>
                    <li>dad</li>
                    <li>dad</li>
                    <li>dad</li>
                    <li>dad</li>
                    <li>dad</li>
                    <li>dad</li>
                    <li>dad</li>
                    <li>dad</li>
                    <li>dad</li>
                    <li>dad</li>
                    <li>dad</li>
                    <li>dad</li>
                    <li>dad</li>
                    <li>dad</li>
                    <li>dad</li>
                    <li>dad</li>
                    <li>dad</li>
                    <li>dad</li>
                    <li>dad</li>
                    <li>dad</li>
                    <li>dad</li>
                    <li>dad</li>
                    <li>dad</li>
                    <li>dad</li>
                    <li>dad</li>
                    <li>dad</li>
                    <li>dad</li>
                    <li>dad</li>
                    <li>dad</li>
                    <li>dad</li>
                    <li>dad</li>
                    <li>dad</li>
                    <li>dad</li>
                    <li>dad</li>
                    <li>dad</li>
                    <li>dad</li>
                    <li>dad</li>
                    <li>dad</li>
                    <li>dad</li>
                    <li>dad</li>
                    <li>dad</li>
                    <li>dad</li>
                    <li>dad</li>
                    <li>dad</li>
                    <li>dad</li>
                    <li>dad</li>
                    <li>dad</li>
                    <li>dad</li>
                    <li>dad</li>
                    <li>dad</li>
                    <li>dad</li>
                    <li>dad</li>
                    <li>dad</li>
                    <li>dad</li>
                    <li>dad</li>
                    <li>dad</li>
                    <li>dad</li>
                    <li>dad</li>
                    <li>dad</li>
                    <li>dad</li>
                    <li>dad</li>
                    <li>dad</li>
                    <li>dad</li>
                    <li>dad</li>
                    <li>dad</li>
                    <li>dad</li>
                    <li>dad</li>
                    <li>dad</li>
                    <li>dad</li>
                    <li>dad</li>
                    <li>dad</li>
                    <li>dad</li>
                    <li>dad</li>
                    <li>dad</li>
                    <li>dad</li>
                </ul>
            </aside>

            <section className='mngo-h-full mngo-overflow-auto md:mngo-w-9/12 mngo-bg-red-900'>
                <div className='md:mngo-mt-28 mngo-mt-2'>
                    {/* <p className="mngo-mt-10 mngo-text-2xl">Learn Mode</p> */}
                    <ul className='mngo-bg-gray-900'>
                        <li>dad</li>
                        <li>dad</li>
                        <li>dad</li>
                        <li>dad</li>
                        <li>dad</li>
                        <li>dad</li>
                        <li>dad</li>
                        <li>dad</li>
                        <li>dad</li>
                        <li>dad</li>
                        <li>dad</li>
                        <li>dad</li>
                        <li>dad</li>
                        <li>dad</li>
                        <li>dad</li>
                        <li>dad</li>
                        <li>dad</li>
                        <li>dad</li>
                        <li>dad</li>
                        <li>dad</li>
                        <li>dad</li>
                        <li>dad</li>
                        <li>dad</li>
                        <li>dad</li>
                        <li>dad</li>
                        <li>dad</li>
                        <li>dad</li>
                        <li>dad</li>
                        <li>dad</li>
                        <li>dad</li>
                        <li>dad</li>
                        <li>dad</li>
                        <li>dad</li>
                        <li>dad</li>
                        <li>dad</li>
                        <li>dad</li>
                        <li>dad</li>
                        <li>dad</li>
                        <li>dad</li>
                        <li>dad</li>
                        <li>dad</li>
                        <li>dad</li>
                        <li>dad</li>
                        <li>dad</li>
                        <li>dad</li>
                        <li>dad</li>
                        <li>dad</li>
                        <li>dad</li>
                        <li>dad</li>
                        <li>dad</li>
                        <li>dad</li>
                        <li>dad</li>
                        <li>dad</li>
                        <li>dad</li>
                        <li>dad</li>
                        <li>dad</li>
                        <li>dad</li>
                        <li>dad</li>
                        <li>dad</li>
                        <li>dad</li>
                        <li>dad</li>
                        <li>dad</li>
                        <li>dad</li>
                        <li>dad</li>
                        <li>dad</li>
                        <li>dad</li>
                        <li>dad</li>
                        <li>dad</li>
                        <li>dad</li>
                        <li>dad</li>
                        <li>dad</li>
                        <li>dad</li>
                        <li>dad</li>
                        <li>dad</li>
                        <li>dad</li>
                        <li>dad</li>
                        <li>dad</li>
                        <li>dad</li>
                        <li>dad</li>
                        <li>dad</li>
                        <li>dad</li>
                        <li>dad</li>
                        <li>dad</li>
                        <li>dad</li>
                        <li>dad</li>
                        <li>dad</li>
                        <li>dad</li>
                        <li>dad</li>
                        <li>dad</li>
                        <li>dad</li>
                        <li>dad</li>
                        <li>dad</li>
                        <li>dad</li>
                        <li>dad</li>
                        <li>dad</li>
                        <li>dad</li>
                    </ul>
                </div>
            </section>
        </section>
    )
}

export default React.memo(LearnMode);